/**
 * @file example.h
 * @brief Auto-generated header for example.c
 *
 * Generated by Header File Generator on 2026-04-15.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef EXAMPLE_H
#define EXAMPLE_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* ─── Includes ────────────────────────────────────────────────────────── */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>


/* ─── Constants / Macros ──────────────────────────────────────────────── */

#define MAX_NAME_LEN 128
#define VERSION_MAJOR 1
#define VERSION_MINOR 0


/* ─── Typedefs ────────────────────────────────────────────────────────── */

typedef unsigned int uint;
typedef char* string_t;


/* ─── Enumerations ────────────────────────────────────────────────────── */

typedef enum Status {
    STATUS_OK = 0,
    STATUS_ERROR,
    STATUS_PENDING,
    STATUS_CANCELLED
} Status;


/* ─── Structures ──────────────────────────────────────────────────────── */

typedef struct Point {
    float x;
    float y;
} Point;

typedef struct Rectangle {
    Point origin;
    float width;
    float height;
} Rectangle;

struct Node {
    int value;
    struct Node* next;
};


/* ─── Function Prototypes ─────────────────────────────────────────────── */

Point point_create(float x, float y);
float point_distance(Point a, Point b);
Rectangle rect_create(Point origin, float width, float height);
float rect_area(Rectangle r);
bool rect_contains_point(Rectangle r, Point p);
Status process_data(const char* input, char* output, size_t output_size);
struct Node node_create(int value);
void node_free(struct Node* node);
void node_list_free(struct Node* head);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* EXAMPLE_H */
